package ch.rasc.twofa.security;

import static ch.rasc.twofa.db.tables.AppUser.APP_USER;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Locale;
import java.util.UUID;

import org.jooq.DSLContext;
import org.jooq.impl.DSL;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.mock.web.MockHttpServletResponse;
import org.springframework.mock.web.MockHttpSession;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.web.context.HttpSessionSecurityContextRepository;
import org.springframework.security.web.csrf.DefaultCsrfToken;

class AuthControllerTest {

	private static final String SECRET = "JBSWY3DPEHPK3PXP";

	private DSLContext dsl;

	private AuthController controller;

	private MockHttpServletRequest request;

	private MockHttpServletResponse response;

	private MockHttpSession session;

	@BeforeEach
	void setUp() {
		this.dsl = DSL.using("jdbc:h2:mem:" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1", "sa", "");
		this.dsl.execute("""
				CREATE TABLE app_user (
				  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				  username VARCHAR(255) NOT NULL UNIQUE,
				  password_hash VARCHAR(255),
				  secret VARCHAR(64),
				  enabled BOOLEAN NOT NULL,
				  additional_security BOOLEAN NOT NULL,
				  last_totp_interval BIGINT
				)
				""");
		this.controller = new AuthController(new TestPasswordEncoder(), this.dsl,
				new HttpSessionSecurityContextRepository());
		this.request = new MockHttpServletRequest();
		this.response = new MockHttpServletResponse();
		this.session = (MockHttpSession) this.request.getSession();
	}

	@AfterEach
	void tearDown() {
		SecurityContextHolder.clearContext();
	}

	@Test
	void passwordLoginRotatesSessionAndPendingTotpSurvivesStatusCheck() {
		insertUser("admin", "password", SECRET);
		String originalSessionId = this.session.getId();

		AuthenticationFlow flow = this.controller.login(" ADMIN ", "password", this.session, this.request,
				this.response);

		assertEquals(AuthenticationFlow.TOTP, flow);
		assertNotEquals(originalSessionId, this.session.getId());
		assertEquals(AuthenticationFlow.TOTP,
				this.controller.authenticate(this.request, new DefaultCsrfToken("X-CSRF", "_csrf", "token")));
		assertFalse(SecurityContextHolder.getContext().getAuthentication() instanceof AppUserAuthentication);
	}

	@Test
	void validTotpCompletesAuthentication() {
		insertUser("admin", "password", SECRET);
		assertEquals(AuthenticationFlow.TOTP,
				this.controller.login("admin", "password", this.session, this.request, this.response));

		String code = currentCode(0);
		assertEquals(AuthenticationFlow.AUTHENTICATED,
				this.controller.totp(code, this.session, this.request, this.response));
		assertTrue(SecurityContextHolder.getContext().getAuthentication() instanceof AppUserAuthentication);
		assertEquals(AuthenticationFlow.AUTHENTICATED,
				this.controller.authenticate(this.request, new DefaultCsrfToken("X-CSRF", "_csrf", "token")));
	}

	@Test
	void usedTotpCodeCannotBeReplayed() {
		insertUser("admin", "password", SECRET);
		this.controller.login("admin", "password", this.session, this.request, this.response);
		String code = currentCode(0);
		assertEquals(AuthenticationFlow.AUTHENTICATED,
				this.controller.totp(code, this.session, this.request, this.response));

		SecurityContextHolder.clearContext();
		this.request = new MockHttpServletRequest();
		this.response = new MockHttpServletResponse();
		this.session = (MockHttpSession) this.request.getSession();
		this.controller.login("admin", "password", this.session, this.request, this.response);

		assertEquals(AuthenticationFlow.TOTP, this.controller.totp(code, this.session, this.request, this.response));
		assertEquals(AuthenticationFlow.AUTHENTICATED,
				this.controller.totp(currentCode(1), this.session, this.request, this.response));
	}

	@Test
	void invalidTotpEscalatesAndInvalidPasswordClearsPendingAuthentication() {
		insertUser("admin", "password", SECRET);
		this.controller.login("admin", "password", this.session, this.request, this.response);
		int validCode = Integer.parseInt(currentCode(0));
		String invalidCode = String.format(Locale.ROOT, "%06d", (validCode + 1) % 1_000_000);

		assertEquals(AuthenticationFlow.TOTP_ADDITIONAL_SECURITY,
				this.controller.totp(invalidCode, this.session, this.request, this.response));
		assertTrue(this.dsl.select(APP_USER.ADDITIONAL_SECURITY)
			.from(APP_USER)
			.where(APP_USER.USERNAME.eq("admin"))
			.fetchSingle(APP_USER.ADDITIONAL_SECURITY));

		assertEquals(AuthenticationFlow.NOT_AUTHENTICATED,
				this.controller.login("admin", "wrong", this.session, this.request, this.response));
		assertEquals(AuthenticationFlow.NOT_AUTHENTICATED,
				this.controller.authenticate(this.request, new DefaultCsrfToken("X-CSRF", "_csrf", "token")));
	}

	@Test
	void additionalSecurityDeterminesClockShiftAndClearsEscalation() {
		insertUser("admin", "password", SECRET);
		this.dsl.update(APP_USER)
			.set(APP_USER.ADDITIONAL_SECURITY, true)
			.where(APP_USER.USERNAME.eq("admin"))
			.execute();
		assertEquals(AuthenticationFlow.TOTP_ADDITIONAL_SECURITY,
				this.controller.login("admin", "password", this.session, this.request, this.response));

		assertEquals(AuthenticationFlow.AUTHENTICATED, this.controller.verifyTotpAdditionalSecurity(currentCode(3),
				currentCode(4), currentCode(5), this.session, this.request, this.response));
		assertEquals("1 minute 30 seconds ahead", this.controller.getTotpShift(this.session));
		assertFalse(this.dsl.select(APP_USER.ADDITIONAL_SECURITY)
			.from(APP_USER)
			.where(APP_USER.USERNAME.eq("admin"))
			.fetchSingle(APP_USER.ADDITIONAL_SECURITY));
	}

	private void insertUser(String username, String password, String secret) {
		this.dsl
			.insertInto(APP_USER, APP_USER.USERNAME, APP_USER.PASSWORD_HASH, APP_USER.SECRET, APP_USER.ENABLED,
					APP_USER.ADDITIONAL_SECURITY)
			.values(username, new TestPasswordEncoder().encode(password), secret, true, false)
			.execute();
	}

	private String currentCode(long shift) {
		long currentInterval = System.currentTimeMillis() / 1000 / 30;
		CustomTotp totp = new CustomTotp(SECRET, () -> currentInterval);
		return String.format(Locale.ROOT, "%06d", totp.generateAtInterval(currentInterval + shift));
	}

}
