package ch.rasc.twofa.security;

import static ch.rasc.twofa.db.tables.AppUser.APP_USER;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Locale;
import java.util.UUID;

import org.jooq.DSLContext;
import org.jooq.impl.DSL;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.mock.web.MockHttpSession;

import com.codahale.passpol.BreachDatabase;
import com.codahale.passpol.PasswordPolicy;

class SignupControllerTest {

	private static final String PASSWORD = "correct horse battery staple 923747";

	private DSLContext dsl;

	private SignupController controller;

	@BeforeEach
	void setUp() {
		this.dsl = DSL.using("jdbc:h2:mem:" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1", "sa", "");
		this.dsl.execute("""
				CREATE TABLE app_user (
				  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				  username VARCHAR(255) NOT NULL UNIQUE,
				  password_hash VARCHAR(255),
				  secret VARCHAR(64),
				  enabled BOOLEAN NOT NULL,
				  additional_security BOOLEAN NOT NULL,
				  last_totp_interval BIGINT
				)
				""");
		PasswordPolicy passwordPolicy = new PasswordPolicy(BreachDatabase.top100K(), 8, 256);
		this.controller = new SignupController(new TestPasswordEncoder(), passwordPolicy, this.dsl);
	}

	@Test
	void signupNormalizesUsernameAndCreatesEnabledPasswordOnlyAccount() {
		MockHttpSession session = new MockHttpSession();

		SignupResponse response = this.controller.signup("  NewUser  ", PASSWORD, false, session);

		assertEquals(SignupResponse.Status.OK, response.status());
		assertNull(response.secret());
		var user = this.dsl.selectFrom(APP_USER).fetchSingle();
		assertEquals("newuser", user.getUsername());
		assertTrue(user.getEnabled());
	}

	@Test
	void totpEnrollmentIsBoundToSessionAndCanBeResumed() {
		MockHttpSession originalSession = new MockHttpSession();
		SignupResponse signup = this.controller.signup("NewUser", PASSWORD, true, originalSession);
		String code = currentCode(signup.secret());

		assertFalse(this.controller.signupConfirmSecret(code, new MockHttpSession()));
		assertFalse(this.dsl.selectFrom(APP_USER).fetchSingle().getEnabled());

		MockHttpSession resumedSession = new MockHttpSession();
		SignupResponse resumed = this.controller.signup("newuser", PASSWORD, true, resumedSession);
		assertEquals(SignupResponse.Status.OK, resumed.status());
		assertEquals(signup.secret(), resumed.secret());
		assertEquals(resumed.secret(), this.controller.pendingSignup(resumedSession).getBody().secret());

		assertTrue(this.controller.signupConfirmSecret(code, resumedSession));
		var enrolledUser = this.dsl.selectFrom(APP_USER).fetchSingle();
		assertTrue(enrolledUser.getEnabled());
		assertNotNull(enrolledUser.getLastTotpInterval());
		assertFalse(this.controller.pendingSignup(resumedSession).hasBody());
	}

	@Test
	void enabledOrWrongPasswordDuplicateCannotResumeEnrollment() {
		MockHttpSession session = new MockHttpSession();
		this.controller.signup("newuser", PASSWORD, true, session);

		SignupResponse wrongPassword = this.controller.signup("NEWUSER", "different password", true,
				new MockHttpSession());
		assertEquals(SignupResponse.Status.USERNAME_TAKEN, wrongPassword.status());

		String code = currentCode(this.dsl.select(APP_USER.SECRET).from(APP_USER).fetchSingle(APP_USER.SECRET));
		assertTrue(this.controller.signupConfirmSecret(code, session));
		SignupResponse enabled = this.controller.signup("newuser", PASSWORD, true, new MockHttpSession());
		assertEquals(SignupResponse.Status.USERNAME_TAKEN, enabled.status());
	}

	private static String currentCode(String secret) {
		long currentInterval = System.currentTimeMillis() / 1000 / 30;
		CustomTotp totp = new CustomTotp(secret, () -> currentInterval);
		return String.format(Locale.ROOT, "%06d", totp.generateAtInterval(currentInterval));
	}

}
