/*
 * This file is generated by jOOQ.
 */
package ch.rasc.twofa.db;

import org.jooq.impl.CatalogImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

  private static final long serialVersionUID = 305001810;

  /**
   * The reference instance of <code>DEFAULT_CATALOG</code>
   */
  public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

  /**
   * No further instances allowed
   */
  private DefaultCatalog() {
    super("");
  }
}
