/*
 * This file is generated by jOOQ.
 */
package ch.rasc.twofa.db;

import ch.rasc.twofa.db.tables.AppUser;
import ch.rasc.twofa.db.tables.records.AppUserRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in the default
 * schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final UniqueKey<AppUserRecord> CONSTRAINT_7 = Internal.createUniqueKey(
      AppUser.APP_USER, DSL.name("CONSTRAINT_7"),
      new TableField[] { AppUser.APP_USER.ID }, true);
  public static final UniqueKey<AppUserRecord> CONSTRAINT_76 = Internal.createUniqueKey(
      AppUser.APP_USER, DSL.name("CONSTRAINT_76"),
      new TableField[] { AppUser.APP_USER.USERNAME }, true);
}
