/*
 * This file is generated by jOOQ.
 */
package ch.rasc.twofa.db.tables.records;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ch.rasc.twofa.db.tables.AppUser;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUserRecord extends UpdatableRecordImpl<AppUserRecord>
    implements Record6<Long, String, String, String, Boolean, Boolean> {

  private static final long serialVersionUID = 1490590862;

  /**
   * Setter for <code>APP_USER.ID</code>.
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>APP_USER.ID</code>.
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>APP_USER.USERNAME</code>.
   */
  public void setUsername(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>APP_USER.USERNAME</code>.
   */
  public String getUsername() {
    return (String) get(1);
  }

  /**
   * Setter for <code>APP_USER.PASSWORD_HASH</code>.
   */
  public void setPasswordHash(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>APP_USER.PASSWORD_HASH</code>.
   */
  public String getPasswordHash() {
    return (String) get(2);
  }

  /**
   * Setter for <code>APP_USER.SECRET</code>.
   */
  public void setSecret(String value) {
    set(3, value);
  }

  /**
   * Getter for <code>APP_USER.SECRET</code>.
   */
  public String getSecret() {
    return (String) get(3);
  }

  /**
   * Setter for <code>APP_USER.ENABLED</code>.
   */
  public void setEnabled(Boolean value) {
    set(4, value);
  }

  /**
   * Getter for <code>APP_USER.ENABLED</code>.
   */
  public Boolean getEnabled() {
    return (Boolean) get(4);
  }

  /**
   * Setter for <code>APP_USER.ADDITIONAL_SECURITY</code>.
   */
  public void setAdditionalSecurity(Boolean value) {
    set(5, value);
  }

  /**
   * Getter for <code>APP_USER.ADDITIONAL_SECURITY</code>.
   */
  public Boolean getAdditionalSecurity() {
    return (Boolean) get(5);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record6 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row6<Long, String, String, String, Boolean, Boolean> fieldsRow() {
    return (Row6) super.fieldsRow();
  }

  @Override
  public Row6<Long, String, String, String, Boolean, Boolean> valuesRow() {
    return (Row6) super.valuesRow();
  }

  @Override
  public Field<Long> field1() {
    return AppUser.APP_USER.ID;
  }

  @Override
  public Field<String> field2() {
    return AppUser.APP_USER.USERNAME;
  }

  @Override
  public Field<String> field3() {
    return AppUser.APP_USER.PASSWORD_HASH;
  }

  @Override
  public Field<String> field4() {
    return AppUser.APP_USER.SECRET;
  }

  @Override
  public Field<Boolean> field5() {
    return AppUser.APP_USER.ENABLED;
  }

  @Override
  public Field<Boolean> field6() {
    return AppUser.APP_USER.ADDITIONAL_SECURITY;
  }

  @Override
  public Long component1() {
    return getId();
  }

  @Override
  public String component2() {
    return getUsername();
  }

  @Override
  public String component3() {
    return getPasswordHash();
  }

  @Override
  public String component4() {
    return getSecret();
  }

  @Override
  public Boolean component5() {
    return getEnabled();
  }

  @Override
  public Boolean component6() {
    return getAdditionalSecurity();
  }

  @Override
  public Long value1() {
    return getId();
  }

  @Override
  public String value2() {
    return getUsername();
  }

  @Override
  public String value3() {
    return getPasswordHash();
  }

  @Override
  public String value4() {
    return getSecret();
  }

  @Override
  public Boolean value5() {
    return getEnabled();
  }

  @Override
  public Boolean value6() {
    return getAdditionalSecurity();
  }

  @Override
  public AppUserRecord value1(Long value) {
    setId(value);
    return this;
  }

  @Override
  public AppUserRecord value2(String value) {
    setUsername(value);
    return this;
  }

  @Override
  public AppUserRecord value3(String value) {
    setPasswordHash(value);
    return this;
  }

  @Override
  public AppUserRecord value4(String value) {
    setSecret(value);
    return this;
  }

  @Override
  public AppUserRecord value5(Boolean value) {
    setEnabled(value);
    return this;
  }

  @Override
  public AppUserRecord value6(Boolean value) {
    setAdditionalSecurity(value);
    return this;
  }

  @Override
  public AppUserRecord values(Long value1, String value2, String value3, String value4,
      Boolean value5, Boolean value6) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached AppUserRecord
   */
  public AppUserRecord() {
    super(AppUser.APP_USER);
  }

  /**
   * Create a detached, initialised AppUserRecord
   */
  public AppUserRecord(Long id, String username, String passwordHash, String secret,
      Boolean enabled, Boolean additionalSecurity) {
    super(AppUser.APP_USER);

    set(0, id);
    set(1, username);
    set(2, passwordHash);
    set(3, secret);
    set(4, enabled);
    set(5, additionalSecurity);
  }
}
