/*
 * This file is generated by jOOQ.
 */
package ch.rasc.twofa.db.tables;

import ch.rasc.twofa.db.DefaultSchema;
import ch.rasc.twofa.db.Keys;
import ch.rasc.twofa.db.tables.records.AppUserRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AppUser extends TableImpl<AppUserRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * The reference instance of <code>APP_USER</code>
   */
  public static final AppUser APP_USER = new AppUser();

  /**
   * The class holding records for this type
   */
  @Override
  public Class<AppUserRecord> getRecordType() {
    return AppUserRecord.class;
  }

  /**
   * The column <code>APP_USER.ID</code>.
   */
  public final TableField<AppUserRecord, Long> ID = createField(DSL.name("ID"),
      SQLDataType.BIGINT.nullable(false).identity(true), this, "");

  /**
   * The column <code>APP_USER.USERNAME</code>.
   */
  public final TableField<AppUserRecord, String> USERNAME = createField(
      DSL.name("USERNAME"), SQLDataType.VARCHAR(255).nullable(false), this, "");

  /**
   * The column <code>APP_USER.PASSWORD_HASH</code>.
   */
  public final TableField<AppUserRecord, String> PASSWORD_HASH = createField(
      DSL.name("PASSWORD_HASH"), SQLDataType.VARCHAR(255), this, "");

  /**
   * The column <code>APP_USER.SECRET</code>.
   */
  public final TableField<AppUserRecord, String> SECRET = createField(DSL.name("SECRET"),
      SQLDataType.VARCHAR(16), this, "");

  /**
   * The column <code>APP_USER.ENABLED</code>.
   */
  public final TableField<AppUserRecord, Boolean> ENABLED = createField(
      DSL.name("ENABLED"), SQLDataType.BOOLEAN.nullable(false), this, "");

  /**
   * The column <code>APP_USER.ADDITIONAL_SECURITY</code>.
   */
  public final TableField<AppUserRecord, Boolean> ADDITIONAL_SECURITY = createField(
      DSL.name("ADDITIONAL_SECURITY"), SQLDataType.BOOLEAN.nullable(false), this, "");

  private AppUser(Name alias, Table<AppUserRecord> aliased) {
    this(alias, aliased, (Field<?>[]) null, null);
  }

  private AppUser(Name alias, Table<AppUserRecord> aliased, Field<?>[] parameters,
      Condition where) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
  }

  /**
   * Create an aliased <code>APP_USER</code> table reference
   */
  public AppUser(String alias) {
    this(DSL.name(alias), APP_USER);
  }

  /**
   * Create an aliased <code>APP_USER</code> table reference
   */
  public AppUser(Name alias) {
    this(alias, APP_USER);
  }

  /**
   * Create a <code>APP_USER</code> table reference
   */
  public AppUser() {
    this(DSL.name("APP_USER"), null);
  }

  @Override
  public Schema getSchema() {
    return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
  }

  @Override
  public Identity<AppUserRecord, Long> getIdentity() {
    return (Identity<AppUserRecord, Long>) super.getIdentity();
  }

  @Override
  public UniqueKey<AppUserRecord> getPrimaryKey() {
    return Keys.CONSTRAINT_7;
  }

  @Override
  public List<UniqueKey<AppUserRecord>> getUniqueKeys() {
    return Arrays.asList(Keys.CONSTRAINT_76);
  }

  @Override
  public AppUser as(String alias) {
    return new AppUser(DSL.name(alias), this);
  }

  @Override
  public AppUser as(Name alias) {
    return new AppUser(alias, this);
  }

  @Override
  public AppUser as(Table<?> alias) {
    return new AppUser(alias.getQualifiedName(), this);
  }

  /**
   * Rename this table
   */
  @Override
  public AppUser rename(String name) {
    return new AppUser(DSL.name(name), null);
  }

  /**
   * Rename this table
   */
  @Override
  public AppUser rename(Name name) {
    return new AppUser(name, null);
  }

  /**
   * Rename this table
   */
  @Override
  public AppUser rename(Table<?> name) {
    return new AppUser(name.getQualifiedName(), null);
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public AppUser where(Condition condition) {
    return new AppUser(getQualifiedName(), aliased() ? this : null, null, condition);
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public AppUser where(Collection<? extends Condition> conditions) {
    return where(DSL.and(conditions));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public AppUser where(Condition... conditions) {
    return where(DSL.and(conditions));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public AppUser where(Field<Boolean> condition) {
    return where(DSL.condition(condition));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  @PlainSQL
  public AppUser where(SQL condition) {
    return where(DSL.condition(condition));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  @PlainSQL
  public AppUser where(@Stringly.SQL String condition) {
    return where(DSL.condition(condition));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  @PlainSQL
  public AppUser where(@Stringly.SQL String condition, Object... binds) {
    return where(DSL.condition(condition, binds));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  @PlainSQL
  public AppUser where(@Stringly.SQL String condition, QueryPart... parts) {
    return where(DSL.condition(condition, parts));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public AppUser whereExists(Select<?> select) {
    return where(DSL.exists(select));
  }

  /**
   * Create an inline derived table from this table
   */
  @Override
  public AppUser whereNotExists(Select<?> select) {
    return where(DSL.notExists(select));
  }
}
